blank_issues_enabled: false
contact_links:
  - name: 📄 Project documentation
    url: https://github.com/UcarMobile/ucm-docs/wiki/Source-Control
    about: Please review the documentation before opening an issue.
