name: 📄 Documentation request
description: Suggest or report an issue related to documentation
labels: [documentation]
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: What needs to be updated or added in the documentation?
  - type: input
    id: jira
    attributes:
      label: Jira / Task Reference
      placeholder: "Example: JIRA-789"

  - type: markdown
    attributes:
      value: |
        **Reminder:**  
        Branch name format → `documentation/#<issue-number>-<short-description>`
