name: 💡 Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
      placeholder: Describe the problem this would solve

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe your idea or how you’d like it implemented

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: Define what must be true for this feature to be considered complete

  - type: input
    id: jira
    attributes:
      label: Jira / Task Reference
      placeholder: "Example: JIRA-456"

  - type: markdown
    attributes:
      value: |
        **Reminder:**  
        Branch name format → `feature/#<issue-number>-<short-description>`
