name: 💡 Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: What feature would you like to see?

  - type: input
    id: jira
    attributes:
      label: Jira / Task Reference
      placeholder: "Example: JIRA-456"

  - type: markdown
    attributes:
      value: |
        **Reminder:**  
        Branch name format → `feature/#<issue-number>-<short-description>`
