name: 💡 Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
      placeholder: Describe the problem this would solve

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe your idea or how you’d like it implemented
