name: PR Body Validation Test

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  test-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: Show PR_BODY variable
        run: |
          echo "PR_BODY from repository variable:"
          echo "${{ vars.PR_BODY }}"

      - name: Validate PR body
        run: |
          # Tomar PR_BODY desde repository variable
          PR_BODY="${{ vars.PR_BODY }}"

          echo "Validating PR_BODY content:"
          echo "$PR_BODY"

          # Regex final
          REGEX='(close|closes|closed|fix|fixes|resolve|resolves)[[:space:]]*#[0-9]+'

          if [[ "$PR_BODY" =~ $REGEX ]]; then
            echo "✅ PR body contains a valid issue-closing reference!"
          else
            echo "❌ PR body does NOT contain a valid issue-closing reference!"
          fi
